project:
  type: website

website:
  page-navigation: true
  title: "ISSS608-VAA"
  
  sidebar: 
    logo: "images/icon VA.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/dneoo/ISSS608-VAA
    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "About this website"
        contents: 
          - text: Home
            href: index.qmd
          - text: About
            href: about.qmd
      - section: "Hands-on Exercise"
        contents: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
      - section: "In-Class Exercise"
        contents:
           - text: "In-class Ex 3"
             href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
      - section: "Take-home Exercise"
        contents: 
          - text: "Take-home Exercise 1"

format:
  html:
    theme: journal
    smooth-scroll: true
    css: styles.css
    toc: true

editor: visual

